### ISSUE TITLE
update: secure the count.txt file

### ISSUE THREAD

**Issue by r3yc0n1c** [ZiaCodes/counter.js#12]
Found a better method for securing the contents of the counter.txt file using a stronger cryptographic protocol.

@ZiaCodes  please assign this issue to me and add the `JWOC`, difficulty level according to you. Thanks in advance.

**Comment by ZiaCodes** [comment]
> Found a better method for securing the contents of the counter.txt file using a stronger cryptographic protocol.
> 
> @ZiaCodes please assign this issue to me and add the `JWOC`, difficulty level according to you. Thanks in advance.

Good luck
