### ISSUE TITLE
Connect frontend to backend

### ISSUE THREAD

**Issue by r3yc0n1c** [ZiaCodes/counter.js#15]
- [x] Create the Node/Express backend
- [x] Connect the React frontend to the backend 

Hey @ZiaCodes please assign this issue to me and add the JWOC tag and difficulty level according to you.
Thanks in advance.

**Comment by ZiaCodes** [comment]
> * [x]  Create the Node/Express backend
> * [x]  Connect the React frontend to the backend
> 
> Hey @ZiaCodes please assign this issue to me and add the JWOC tag and difficulty level according to you. Thanks in advance.

Okay assigning
