### ISSUE TITLE
Render a random Youtube Music Video

### ISSUE THREAD

**Issue by ZiaCodes** [ZiaCodes/counter.js#3]
Render a random Youtube Music Video When the counter will reach 1000 or multiple of 1000.

Note: Before making pull request make sure you have done all the work and please add some necessary gifs and photos.

**Comment by privateyash** [comment]
"I want to work on this issue under JWOC"

**Comment by ZiaCodes** [comment]
> "I want to work on this issue under JWOC"

Okay done ✅

**Comment by ronitblenz** [comment]
Hi, I would want to look into this?

**Comment by ZiaCodes** [comment]
> Hi, I would want to look into this?

max - 02 issues at a time

**Comment by r3yc0n1c** [comment]
I would like to work on this issue under JWOC

**Comment by ZiaCodes** [comment]
> I would like to work on this issue under JWOC

Okay done ✅
